### ISSUE TITLE
Invalid time format is accepted

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#122] opened 2018-11-02 16:11 UTC
**Describe the bug**
While adding the task to be done, invalid time format is accepted.

**To Reproduce**
1. open the app
2. input task n/Submission b/CG2027 assign2 s/54/10 e/83/10_1400 p/HIGH t/IVLE
3. the task will be added
4. start time of 54 of Oct or 83 Oct are not valid time 

**Expected behavior**
task can still be added even the format is not valid
**Screenshots**
![screen shot 2018-11-02 at 17 40 47](https://user-images.githubusercontent.com/34418860/47908099-88378c00-dec7-11e8-809a-d8c10119d482.png)
![screen shot 2018-11-02 at 17 41 20](https://user-images.githubusercontent.com/34418860/47908106-8b327c80-dec7-11e8-9de9-400f3e3aa0bb.png)

**Additional context**
Nil

<hr>

**Reported by:** @ftywan
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#612]</sub>

**Comment by luhan02** [comment] 2018-11-02 16:40
Duplicate of #111

**Closed as completed** 2018-11-02 17:41 UTC
Labels: duplicate
