### ISSUE TITLE
T13-1: Wrong message displayed in updateTask

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#118] opened 2018-11-02 16:02 UTC
**Describe the bug**
When the updateTask command is run, even though the task is updated in the list, the message displayed is "This task already exists in the task book." 

**To Reproduce**
1. Go to the GUI
2. Make sure there are existing tasks in the list.
3. updateTask 1 n/shopping
4. See that the list is updated but the message displayed says that the task already exists in the task book.

**Expected behavior**
I expect to see a message saying, task is updated successfully!

**Screenshots**
![image](https://user-images.githubusercontent.com/28647601/47907443-3b9f8100-dec6-11e8-9a27-9cd9e5315540.png)

**Additional context**

<hr>

**Reported by:** @kangmingtay
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#450]</sub>

**Comment by luhan02** [comment] 2018-11-02 16:31
Duplicate of #107

**Closed as completed** 2018-11-02 17:41 UTC
Labels: duplicate
