### ISSUE TITLE
Adding a task that has an impossible date

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#112] opened 2018-11-02 15:13 UTC
**Describe the bug**
31/02 and 33/02 is not captured as an impossible date when adding a task.

**To Reproduce**
1. Execute the command task n/name5 b/body s/31/02 e/33/02 p/HIGH t/hi
2. A task with the start date of 31/02 to 33/02 is added into the list of tasks

**Expected behavior**
Adds a task that has a proper date.

**Screenshots**
![image](https://user-images.githubusercontent.com/35420846/47906753-deef9680-dec4-11e8-9045-de4bbb3309d5.png)

<hr>

**Reported by:** @ladderinc
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#357]</sub>

**Comment by luhan02** [comment] 2018-11-02 16:34
Duplicate of #110

**Closed as completed** 2018-11-02 17:43 UTC
Labels: duplicate
