### ISSUE TITLE
Can update start date of tasks to impossible date

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#126] opened 2018-11-02 16:16 UTC
**Describe the bug**
As described in title.

**To Reproduce**
1. Execute the command updateTask s/99/10

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35420846/47908455-34797280-dec8-11e8-8b19-38f04d7319f6.png)

<hr>

**Reported by:** @ladderinc
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#718]</sub>

**Comment by luhan02** [comment] 2018-11-02 16:37
Duplicate of #110

**Comment by luhan02** [comment] 2018-11-02 16:39
Duplicate of #110

**Closed as completed** 2018-11-02 17:41 UTC
Labels: duplicate
